language: php
php:
  - 7.1
install:
  - /home/travis/.phpenv/versions/7.1/bin/composer install
  - phpenv rehash
before_script:
  - mkdir -p build/logs
script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-coveralls -v
